name: Task
description: 새로운 작업(Task)을 생성합니다
title: '[TASK] '
labels: ['enhancement']
assignees: ['@me']
body:
  - type: markdown
    attributes:
      value: |
        ## Task 이슈를 생성합니다
        작업에 대한 상세 정보를 입력해주세요.

  - type: input
    id: task-title
    attributes:
      label: Task Title
      description: 작업의 제목을 입력하세요
      placeholder: '예: 로그인 API 구현'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: 무엇을, 왜 수행해야 하는지 설명합니다
      placeholder: |
        이 작업의 목적과 배경을 설명해주세요.
        - 왜 이 작업이 필요한가?
        - 어떤 문제를 해결하는가?
    validations:
      required: true

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: 완료 조건(Acceptance Criteria)
      description: 이 작업이 완료되었다고 판단할 수 있는 조건들
      options:
        - label: AC 1
        - label: AC 2
        - label: AC 3

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: 테스트 가능하거나 사용 가능한 결과물
      placeholder: |
        - 구현된 기능
        - 테스트 코드
        - 문서
        - PR 링크
    validations:
      required: true

  - type: input
    id: related-epic
    attributes:
      label: Related Epic
      description: 연관된 Epic의 Milestone 번호를 입력하세요
      placeholder: 'Milestone: [EPIC] <Name>'

  - type: textarea
    id: linked-subtasks
    attributes:
      label: Linked Sub-tasks
      description: 연관된 하위 작업 이슈 번호
      placeholder: |
        - #123
        - #456
